version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2
    environment:
      TZ: "/usr/share/zoneinfo/America/Argentina/Buenos_Aires"
    paralelism: 2
    branch:
      only:
        - source
    steps:
      - run: git config --global user.email "tadp.bot@gmail.com"
      - run: git config --global user.name "GreypineCI"
      - checkout
      - run:
        - name: Install dependencies
        - command: bundle install --jobs=10 --retry=3
      - run:
        - name: Run the tests for backend
        - command: bundle exec rake test
      - run:
        - name: Publishing
        - command: bundle exec rake publish

workflows:
  version: 2
  build_and_publish:
    jobs:
    - build